version: '3'
services: 
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'backend_test'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: 
      - "3306:3306"
    volumes:
    - mysqlbkp:/var/lib/mysql
  
  mongo:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: backend_test
    volumes:
    - mongobkp:/data/db

  nodejs:
    build:
      context: .
    command: [ "sh", "/app/start.sh" ]      
    depends_on:
      - mysql    
    ports:
      - "8080:3000"

volumes:
  mongobkp:
    external: true
  mysqlbkp:
    external: true
